name: integration_test_permissions
description: >
  Sample demonstrating how to handle permissions with the integration_test
  package
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^3.0.0
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: any
flutter:
  uses-material-design: true
